routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('apartments', 'ApartmentController');
Route::resource('participation', 'ParticipationController');
Route::resource('tasks', 'TasksController');
Route::resource('payments', 'PaymentsController');

Route::get('/participate', 'ParticipationController@store')->name('participation.store');
Route::get('/tasks/create','TasksController@new')->name('tasks.new');

Route::get('/disparticipate', 'ParticipationController@destroy')->name('participation.destroy');

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="ml-auto">
            <a href="{{route('apartments.create')}}" class="btn btn-outline-primary">Добавить объект</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            @if(auth()->user()->apartments->count() > 0)
            <h2>Мои объекты</h2>
            <div class="mt-4 card-columns">
                @foreach(auth()->user()->apartments as $apartment)
                    @include('apartments._card')
                @endforeach
            </div>
            @else
                <a href="{{route('apartments.create')}}"><h2>Добавьте свой первый объект</h2></a>
            @endif
        </div>
    </div>
    <div class="row mt-4">
        <div class="col-md-12">
            @if(auth()->user()->participations->count() > 0)
                <h2>Обекты доступные мне</h2>
                <div class="mt-4 card-columns">
                    @foreach(auth()->user()->participations as $apartment)
                        @include('apartments._card')
                    @endforeach
                </div>
            @endif
        </div>
    </div>
</div>
@endsection