routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('apartments', 'ApartmentController');
Route::resource('participation', 'ParticipationController');
Route::resource('tasks', 'TasksController');
Route::resource('payments', 'PaymentsController');

Route::get('/participate', 'ParticipationController@store')->name('participation.store');
Route::get('/tasks/create','TasksController@new')->name('tasks.new');

Route::get('/disparticipate', 'ParticipationController@destroy')->name('participation.destroy');

app/Tasks.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tasks extends Model
{
    protected $fillable = [
        'name',
        'budget',
        'apartment_id'
        ];

    public function apartments()
    {
        return $this->belongsTo(Apartment::class);
    }

    public function payments()
    {
        return $this->hasMany(Payments::class);
    }

}

app/Http/Controllers/TasksController.php
<?php

namespace App\Http\Controllers;

use App\Apartment;
use App\Tasks;
use Illuminate\Http\Request;

class TasksController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function new(Apartment $apartment)
    {
        return view('tasks.create', compact('apartment'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'budget' => 'required',
            'apartment_id' => 'required',
        ]);


        $task = Tasks::create([
            'name' => $request->name,
            'budget' => $request->budget,
            'apartment_id' => $request->apartment_id,
        ]);

        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Tasks  $tasks
     * @return \Illuminate\Http\Response
     */
    public function show(Tasks $tasks)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Tasks  $tasks
     * @return \Illuminate\Http\Response
     */
    public function edit(Tasks $tasks)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Tasks  $tasks
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Tasks $tasks)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Tasks  $tasks
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tasks $tasks)
    {
        //
    }
}

resources/views/tasks/_card.blade.php
<a href="{{route('apartments.show', $apartment)}}">
    <div class="card text-decoration-none">
        <div class="card-header h4">
            {{$apartment->name}}
        </div>
        <div class="card-body">
            {{$apartment->address}}
        </div>
    </div>
</a>

resources/views/tasks/_form.blade.php
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Добавление задачи</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                    <div class="form-group">
                        {{ Form::label('name', 'Название задачи') }}
                        {{ Form::text('name', null, ['class' => 'form-control']) }}
                    </div>

                    {{Form::hidden('apartment_id', $apartment->id)}}

                    <div class="form-group">
                        {{ Form::label('budget', 'Бюджет') }}
                        {{ Form::number('budget', null, ['class' => 'form-control']) }}
                    </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                {{  Form::submit('Сохранить', ['class' => 'btn btn-primary']) }}
            </div>
        </div>
    </div>
</div>

resources/views/tasks/create.blade.php
        {{ Form::open(['role' => 'form', 'id' => 'tasks-form', 'route' => 'tasks.store', 'method' => 'post']) }}
        @include('tasks._form')
        {{ Form::close() }}

resources/views/tasks/edit.blade.php
@extends('layouts._app')

@section('content')
    <div class="container">
        {{ Form::model($apartment,['role' => 'form', 'id' => 'apartmentss-form', 'route' => ['apartments.update',$apartment], 'method' => 'put']) }}
        @include('apartments._form')
        {{ Form::close() }}
    </div>
@endsection

resources/views/tasks/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">

        </div>
    </div>
{{--    <div class="row">--}}
{{--        <div class="ml-auto">--}}
{{--            <a href="{{route('apartments.destroy', $apartment)}}" class="btn btn-outline-danger">Удалить объект</a>--}}
{{--        </div>--}}
{{--    </div>--}}
    <div class="row">
        <div class="col-md-12 text-center">
                <h1>{{$apartment->name}}</h1>
            <div class="text-truncate">{{$apartment->address}}</div>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col-md-4">
            <div class="card">
                <div class="card-header">
                    Расходы по категориям
                </div>
                <div class="card-body">
                    Тут будет круговая диаграмма, когда-то
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    Добавление расхода
                </div>
                <div class="card-body">

                </div>
            </div>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col-md-4">
            <div class="card">
                <div class="card-header">
                    Участники проекта
                </div>
                <div class="card-body">
                    <table class="table">
                        <thead>
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Удаление</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            @foreach($apartment->users as $user)
                                <tr>
                                    <td>{{$user->name}}</td>
                                    <td>
                                        <form method="GET" action="{{ route('participation.destroy') }}">
                                                <input type="hidden" name="apartment_id" value="{{$apartment->id}}">
                                                <input type="hidden" value="{{$user->id}}" name="id">
                                                <button class="btn btn-block btn-secondary">Удалить</button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tr>
                        </tbody>
                    </table>

                </div>
                <div class="card-footer">
                    <form method="GET" action="{{ route('participation.store') }}">
                        <div class="input-group my-2">

                                <input type="hidden" name="apartment_id" value="{{$apartment->id}}">
                                <input type="text" class="form-control" placeholder="Email" name="email">
                            <div class="input-group-append">
                                <button class="btn btn-block btn-success">Добавить</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>

        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    Задачи проекта
                </div>
                <div class="card-body">
                    @foreach($apartment->tasks as $task)
                        <a href="{{route('tasks.show', $task)}}">{{$task->name}}</a>
                    @endforeach
                </div>
            </div>

        </div>
    </div>
</div>
@endsection